config/routes.rb
Rails.application.routes.draw do
  resources :user_sessions, only: %i[new create destroy]
  resources :events, only: %i[index new create show]
  get 'login' => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'
  post 'assist_event' => 'events#assist_event'
  resources :users
  root to: 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee_event.rb
class AttendeeEvent < ApplicationRecord
  belongs_to :attendee, class_name: 'User', foreign_key: 'user_id', inverse_of: :attended_events
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id', inverse_of: :created_events
  has_many :attendee_events, dependent: :destroy
  has_many :attendees, through: :attendee_events, class_name: 'User', foreign_key: 'user_id'
  scope :upcoming_events, -> { where('date > ?', Time.zone.today.strftime('%Y-%m-%d')).order(date: :asc) }
  scope :past_events, -> { where('date <= ?', Time.zone.today.strftime('%Y-%m-%d')).order(date: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :created_events, class_name: 'Event', foreign_key: 'user_id', dependent: :destroy, inverse_of: :creator
  has_many :attendee_events, dependent: :destroy
  has_many :attended_events, through: :attendee_events, source: :event, foreign_key: 'user_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    @current_user ||= User.find(session[:id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  helper_method :current_user, :assist_event
  before_action :user_authenticated

  def index
    @events = Event.select('events.*, users.id user_id, users.name creator_name').joins(:creator)
    @past_events = @events.past_events
    @upcoming_events = @events.upcoming_events
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def show
    @event = Event.find(params[:id])
    @attendees = User.find_by_sql(['SELECT u.id, u.name FROM users u JOIN attendee_events e ON e.user_id = u.id WHERE e.event_id = ?', params[:id]])
    current_user
  end

  def assist_event
    current_user
    AttendeeEvent.create(user_id: @current_user.id, event_id: params[:event_id])
    redirect_to event_url(id: params[:event_id])
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :date, :user_id)
  end

  def user_authenticated
    redirect_to login_path unless session[:name]
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :user_authenticated, only: [:new]
  def new; end

  def create
    if find_user
      session[:name] = params[:name]
      session[:id] = @current_user.id

      redirect_to(root_path, notice: 'Logged in successfully.')
    else
      flash.now.alert = 'Login failed.'
      render action: :new
    end
  end

  def destroy
    reset_session
    redirect_to(:login, notice: 'Logged out!')
  end

  private

  def find_user
    @current_user = User.find_by(name: params[:name])
  end

  def user_authenticated
    redirect_to events_path if session[:name]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_authenticated, only: %i[index show]
  include UserHelper

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:name] = params[:name]
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def show
    @user = User.find(params[:id])
    @events = @user.created_events
    @upcoming_events = @user.created_events.upcoming_events
    @past_events = @user.created_events.past_events
  end

  private

  def user_params
    params.require(:user).permit(:name, :password)
  end

  def user_authenticated
    redirect_to root_path unless session[:name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:id])
  end
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def assist(event_id)
    html = ''
    html += if !current_user.attended_events.exists?(event_id)
              button_to 'Attend', assist_event_path(event_id: event_id), { class: 'btn btn-primary' }
            else
              button_to 'Attend', assist_event_path(event_id: event_id), { class: 'btn btn-secondary', disabled: true }
            end

    html.html_safe
  end

  def events_list(events)
    html = ''
    events.each do |e|
      html += <<-HTML
      <tr scope="row">
        <td>#{e.name}</td>
        <td>#{e.description}</td>
        <td>#{e.date}</td>
        <td>#{e.creator.name}</td>
        <td>#{link_to 'view', e}</td>
      </tr>
      HTML
    end
    html.html_safe
  end

  def attendees_list(attendees)
    html = ''

    attendees.each do |a|
      html += <<-HTML
      <div class="row">
      <p>#{a.name}</p>
      </div>
      HTML
    end
    html.html_safe
  end
end

app/helpers/user_helper.rb
module UserHelper
  def users_list(users)
    html = ''
    users.each do |u|
      html += <<-HTML
          <tr scope="row">
          <td>#{u.name}</td>
          </tr>
      HTML
    end
    html.html_safe
  end
end

app/views/events/_events.html.erb
  <table class="table table-striped border">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Date</th>
        <th scope="col">Creator</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <%= events_list(events) %>
    </tbody>
  </table>

app/views/events/index.html.erb
<h2 class="text-primary text-center">Events List</h2>

<div class="container">
  <div class="row">
    <%= render partial: 'events', locals: {events: @events} %>
  </div>

  <div class="row">
    <h3 class="text-info">Upcoming events</h3>
    <%= render partial: 'events', locals: {events: @upcoming_events} %>
  </div>

  <div class="row">
    <h3 class="text-info">Previously events</h3>
    <%= render partial: 'events', locals: {events: @past_events} %>
  </div>
</div>

app/views/events/index.html_BACKUP_20350.erb
<<<<<<< HEAD
<div class="container">
  <h1>Events</h1>
    <div class="row">
      <div class="col">Name</div>
      <div class="col">Description</div>
      <div class="col">Date</div>
      <div class="col">Creator</div>
    </div>
    <% @events.each do |e| %>
      <div class="row">
        <div class="col">
          <%= e.name %>
        </div>
        <div class="col">
          <%= e.description %>
        </div>
        <div class="col">
          <%= e.date %>
        </div>
        <div class="col">
          <%= e.creator_name %>
        </div>
      </div>
    <% end %>
</div>
=======
<div class="border backgroundWhite">
  <div class="row">
        <div class="col-6">
            <h2 class="text-info">Event List</h2>
        </div>
    </div>
    <br />
<div>
<table class="table table-striped border">
  <tr>
      <th class="table-secondary">
          Name
      </th>
      <th class="table-secondary">Description</th>
      <th class="table-secondary">Date</th>
      <th class="table-secondary">Creator</th>
  </tr>
  <% @events.each do |e| %>
    <tr>
      <td class="col-2">
        <%= e.name %>
      </td>
      <td class="col-6">
        <%= e.description %>
      </td>
      <td class="col-2">
        <%= e.date %>
      </td>
      <td class="col-2">
        <%= e.creator_name %>
      </td>
    </tr>
  <% end %>
</table>
>>>>>>> ad0dadd095b1efc553356c40ff3562dda443b6b8

app/views/events/new.html.erb
<h1 class="text-center text-primary">Create Event</h1>
<div class="d-flex justify-content-center">
  <%= form_for [@user, @event] do |e| %>
    <div class="form-group">
      <p><%= e.label :name, nil %></p>
      <p><%= e.text_field :name, class: 'form-control' %></p>
    </div>
    <div class="form-group">
      <p><%= e.label :description %></p>
      <p><%= e.text_area :description, class: 'form-control' %></p>
    </div>
    <div class="form-group">
      <p><%= e.label :date %></p>
      <p><%= e.date_field :date, class: 'form-control' %></p>
    </div>
    <div class="form-row text-center">
      <div class="col-12">
        <%= e.submit 'Create', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<h1 class="text-center text-primary">Event</h1>

<div class="container">
  <div class="row">
    <p><span class="font-weight-bold">Name:</span> <%= @event.name %></p>
  </div>
  <div class="row">
    <p><span class="font-weight-bold">Description:</span> <%= @event.description %></p>
  </div>
  <div class="row">
    <p><span class="font-weight-bold">Date:</span> <%= @event.date %></p>
  </div>
  <div class="row">
    <p><span class="font-weight-bold">Creator:</span> <%= @event.creator.name %></p>
  </div>

  <div class="row justify-content-center">
    <%= assist(@event.id) %>
  </div>

  <h2 class="text-center text-primary m-4">Attendees</h2>

  <%= attendees_list(@attendees) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>
  </head>

  <body>
    <%= render 'shared/nav_menu' if session[:name] %>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav_menu.html.erb
<% if session[:name] %>
  <div class="container">
    <header class="d-flex justify-content-between">
      <ul class="nav justify-content-center">
        <li class="nav-item pr-3"><%= link_to 'Events', events_path %></li>
        <li class="nav-item pr-3"><%= link_to 'Users', users_path %></li>
        <li class="nav-item pr-3"><%= link_to 'My Events', user_path(session[:id]) %></li>
      </ul>
      <ul class="nav justify-content-end">
        <li class="nav-item"></li>
        <li class="nav-item"><%= link_to 'Create Event', new_event_path %></li>
        <% if session[:name] %>
          <li class="nav-item pl-3"><%= link_to 'Logout', logout_path %></li>
        <% else %>
          <li class="nav-item"><a href="">Login</a></li>
        <% end %>
      </ul>
    </header>
  </div>
<% end %>

app/views/user/new.html.erb
<h1>Sign Up</h1>
<% form_for @user do |u| %>
  <div>
    <p><%= u.label :name %></p>
    <p><%= u.text_field :name %></p>
  </div>
  <div>
    <p><%= u.label :password %></p>
    <p><%= u.text_field :password %></p>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1 class="text-center text-primary">Login</h1>
<div class="d-flex justify-content-center">
  <%= form_tag user_sessions_path, method: :post do %>
    <div class="form-group">
      <%= label_tag :name, nil, class: 'col col-form-label' %>
      <div class="col">
        <%= text_field_tag :name, nil, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag :password, nil, class: 'col col-form-label' %>
      <div class="col">
        <%= password_field_tag :password, nil, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group text-center"><%= link_to  'Create account', new_user_path %></div>
    <div class="form-row text-center">
      <div class="col-12">
        <%= submit_tag "Login", class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h2 class="text-primary text-center">Users</h2>
<div class="container">
  <div class="row">
    <table class="table table-striped border">
    <thead>
      <tr>
        <th scope="col">Name</th>
      </tr>
    </thead>
    <tbody>
      <%= users_list(@users) %>
    </tbody>
  </div>
</div>

app/views/users/new.html.erb
<h1 class="text-center text-primary">Sign Up</h1>
<div class="d-flex justify-content-center">
  <%= form_for @user do |u| %>
    <div class="form-group">
      <%= u.label :name, class: 'col col-form-label' %>
      <div class="col">
        <%= u.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= u.label :password, class: 'col col-form-label' %>
      <div class="col">
        <%= u.password_field :password, class: 'form-control' %>
      </div>
    </div>
    <div class="form-row text-center">
      <div class="col-12">
        <%= u.submit 'Sign Up', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container mt-4">
  <h2 class="text-info">Profile Page</h2>
  <div>
    <p class="lead">User: <%= @user.name %></p>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @user.attended_events do |e| %>
      <%= e.description %>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <%= render partial: 'events/events', locals: {events: @events} %>
  </div>

  <div class="row">
    <h3 class="text-info">Upcoming events</h3>
    <%= render partial: 'events/events', locals: {events: @upcoming_events} %>
  </div>

  <div class="row">
    <h3 class="text-info">Previously events</h3>
    <%= render partial: 'events/events', locals: {events: @past_events} %>
  </div>
</div>